# Generated by Django 5.1.6 on 2025-03-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_tax_options'),
        ('orders', '0004_alter_order_tax_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ManyToManyField(blank=True, to='marketplace.cart'),
        ),
    ]
